from enum import StrEnum, auto


class FactionSymbol(StrEnum):
    COSMIC = auto()
    VOID = auto()
    GALACTIC = auto()
    QUANTUM = auto()
    DOMINION = auto()


class ShipStatus(StrEnum):
    IN_TRANSIT = auto()
    IN_ORBIT = auto()
    DOCKED = auto()


class FlightMode(StrEnum):
    DRIFT = auto()
    STEALTH = auto()
    CRUISE = auto()
    BURN = auto()


class ShipType(StrEnum):
    SHIP_PROBE = auto()
    SHIP_MINING_DRONE = auto()
    SHIP_INTERCEPTOR = auto()
    SHIP_LIGHT_HAULER = auto()
    SHIP_COMMAND_FRIGATE = auto()
    SHIP_EXPLORER = auto()
    SHIP_HEAVY_FREIGHTER = auto()
    SHIP_LIGHT_SHUTTLE = auto()
    SHIP_ORE_HOUND = auto()
    SHIP_REFINING_FREIGHTER = auto()


class WaypointType(StrEnum):
    PLANET = auto()
    GAS_GIANT = auto()
    MOON = auto()
    ORBITAL_STATION = auto()
    JUMP_GATE = auto()
    ASTEROID_FIELD = auto()
    NEBULA = auto()
    DEBRIS_FIELD = auto()
    GRAVITY_WELL = auto()


class WaypointTrait(StrEnum):
    UNCHARTED = auto()
    MARKETPLACE = auto()
    SHIPYARD = auto()
    OUTPOST = auto()
    SCATTERED_SETTLEMENTS = auto()
    SPRAWLING_CITIES = auto()
    MEGA_STRUCTURES = auto()
    OVERCROWDED = auto()
    HIGH_TECH = auto()
    CORRUPT = auto()
    BUREAUCRATIC = auto()
    TRADING_HUB = auto()
    INDUSTRIAL = auto()
    BLACK_MARKET = auto()
    RESEARCH_FACILITY = auto()
    MILITARY_BASE = auto()
    SURVEILLANCE_OUTPOST = auto()
    EXPLORATION_OUTPOST = auto()
    MINERAL_DEPOSITS = auto()
    COMMON_METAL_DEPOSITS = auto()
    PRECIOUS_METAL_DEPOSITS = auto()
    RARE_METAL_DEPOSITS = auto()
    METHANE_POOLS = auto()
    ICE_CRYSTALS = auto()
    EXPLOSIVE_GASES = auto()
    STRONG_MAGNETOSPHERE = auto()
    VIBRANT_AURORAS = auto()
    SALT_FLATS = auto()
    CANYONS = auto()
    PERPETUAL_DAYLIGHT = auto()
    PERPETUAL_OVERCAST = auto()
    DRY_SEABEDS = auto()
    MAGMA_SEAS = auto()
    SUPERVOLCANOES = auto()
    ASH_CLOUDS = auto()
    VAST_RUINS = auto()
    MUTATED_FLORA = auto()
    TERRAFORMED = auto()
    EXTREME_TEMPERATURES = auto()
    EXTREME_PRESSURE = auto()
    DIVERSE_LIFE = auto()
    SCARCE_LIFE = auto()
    FOSSILS = auto()
    WEAK_GRAVITY = auto()
    STRONG_GRAVITY = auto()
    CRUSHING_GRAVITY = auto()
    TOXIC_ATMOSPHERE = auto()
    CORROSIVE_ATMOSPHERE = auto()
    BREATHABLE_ATMOSPHERE = auto()
    JOVIAN = auto()
    ROCKY = auto()
    VOLCANIC = auto()
    FROZEN = auto()
    SWAMP = auto()
    BARREN = auto()
    TEMPERATE = auto()
    JUNGLE = auto()
    OCEAN = auto()
    STRIPPED = auto()


class Goods(StrEnum):
    PRECIOUS_STONES = auto()
    QUARTZ_SAND = auto()
    SILICON_CRYSTALS = auto()
    AMMONIA_ICE = auto()
    LIQUID_HYDROGEN = auto()
    LIQUID_NITROGEN = auto()
    ICE_WATER = auto()
    EXOTIC_MATTER = auto()
    ADVANCED_CIRCUITRY = auto()
    GRAVITON_EMITTERS = auto()
    IRON = auto()
    IRON_ORE = auto()
    COPPER = auto()
    COPPER_ORE = auto()
    ALUMINUM = auto()
    ALUMINUM_ORE = auto()
    SILVER = auto()
    SILVER_ORE = auto()
    GOLD = auto()
    GOLD_ORE = auto()
    PLATINUM = auto()
    PLATINUM_ORE = auto()
    DIAMONDS = auto()
    URANITE = auto()
    URANITE_ORE = auto()
    MERITIUM = auto()
    MERITIUM_ORE = auto()
    HYDROCARBON = auto()
    ANTIMATTER = auto()
    FERTILIZERS = auto()
    FABRICS = auto()
    FOOD = auto()
    JEWELRY = auto()
    MACHINERY = auto()
    FIREARMS = auto()
    ASSAULT_RIFLES = auto()
    MILITARY_EQUIPMENT = auto()
    EXPLOSIVES = auto()
    LAB_INSTRUMENTS = auto()
    AMMUNITION = auto()
    ELECTRONICS = auto()
    SHIP_PLATING = auto()
    EQUIPMENT = auto()
    FUEL = auto()
    MEDICINE = auto()
    DRUGS = auto()
    CLOTHING = auto()
    MICROPROCESSORS = auto()
    PLASTICS = auto()
    POLYNUCLEOTIDES = auto()
    BIOCOMPOSITES = auto()
    NANOBOTS = auto()
    AI_MAINFRAMES = auto()
    QUANTUM_DRIVES = auto()
    ROBOTIC_DRONES = auto()
    CYBER_IMPLANTS = auto()
    GENE_THERAPEUTICS = auto()
    NEURAL_CHIPS = auto()
    MOOD_REGULATORS = auto()
    VIRAL_AGENTS = auto()
    MICRO_FUSION_GENERATORS = auto()
    SUPERGRAINS = auto()
    LASER_RIFLES = auto()
    HOLOGRAPHICS = auto()
    SHIP_SALVAGE = auto()
    RELIC_TECH = auto()
    NOVEL_LIFEFORMS = auto()
    BOTANICAL_SPECIMENS = auto()
    CULTURAL_ARTIFACTS = auto()
    REACTOR_SOLAR_I = auto()
    REACTOR_FUSION_I = auto()
    REACTOR_FISSION_I = auto()
    REACTOR_CHEMICAL_I = auto()
    REACTOR_ANTIMATTER_I = auto()
    ENGINE_IMPULSE_DRIVE_I = auto()
    ENGINE_ION_DRIVE_I = auto()
    ENGINE_ION_DRIVE_II = auto()
    ENGINE_HYPER_DRIVE_I = auto()
    MODULE_MINERAL_PROCESSOR_I = auto()
    MODULE_CARGO_HOLD_I = auto()
    MODULE_CREW_QUARTERS_I = auto()
    MODULE_ENVOY_QUARTERS_I = auto()
    MODULE_PASSENGER_CABIN_I = auto()
    MODULE_MICRO_REFINERY_I = auto()
    MODULE_ORE_REFINERY_I = auto()
    MODULE_FUEL_REFINERY_I = auto()
    MODULE_SCIENCE_LAB_I = auto()
    MODULE_JUMP_DRIVE_I = auto()
    MODULE_JUMP_DRIVE_II = auto()
    MODULE_JUMP_DRIVE_III = auto()
    MODULE_WARP_DRIVE_I = auto()
    MODULE_WARP_DRIVE_II = auto()
    MODULE_WARP_DRIVE_III = auto()
    MODULE_SHIELD_GENERATOR_I = auto()
    MODULE_SHIELD_GENERATOR_II = auto()
    MOUNT_GAS_SIPHON_I = auto()
    MOUNT_GAS_SIPHON_II = auto()
    MOUNT_GAS_SIPHON_III = auto()
    MOUNT_SURVEYOR_I = auto()
    MOUNT_SURVEYOR_II = auto()
    MOUNT_SURVEYOR_III = auto()
    MOUNT_SENSOR_ARRAY_I = auto()
    MOUNT_SENSOR_ARRAY_II = auto()
    MOUNT_SENSOR_ARRAY_III = auto()
    MOUNT_MINING_LASER_I = auto()
    MOUNT_MINING_LASER_II = auto()
    MOUNT_MINING_LASER_III = auto()
    MOUNT_LASER_CANNON_I = auto()
    MOUNT_MISSILE_LAUNCHER_I = auto()
    MOUNT_TURRET_I = auto()


class ContractType(StrEnum):
    PROCUREMENT = auto()
    TRANSPORT = auto()
    SHUTTLE = auto()
